//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 8/20/2010 2:47:18 PM
namespace RestdModel
{
    
    /// <summary>
    /// There are no comments for RestdEntities in the schema.
    /// </summary>
    public partial class RestdEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new RestdEntities object using the connection string found in the 'RestdEntities' section of the application configuration file.
        /// </summary>
        public RestdEntities() : 
                base("name=RestdEntities", "RestdEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new RestdEntities object.
        /// </summary>
        public RestdEntities(string connectionString) : 
                base(connectionString, "RestdEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new RestdEntities object.
        /// </summary>
        public RestdEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "RestdEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for EO_ANIMAL in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EO_ANIMAL> EO_ANIMAL
        {
            get
            {
                if ((this._EO_ANIMAL == null))
                {
                    this._EO_ANIMAL = base.CreateQuery<EO_ANIMAL>("[EO_ANIMAL]");
                }
                return this._EO_ANIMAL;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EO_ANIMAL> _EO_ANIMAL;
        /// <summary>
        /// There are no comments for EO_NATURAL_COMM in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EO_NATURAL_COMM> EO_NATURAL_COMM
        {
            get
            {
                if ((this._EO_NATURAL_COMM == null))
                {
                    this._EO_NATURAL_COMM = base.CreateQuery<EO_NATURAL_COMM>("[EO_NATURAL_COMM]");
                }
                return this._EO_NATURAL_COMM;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EO_NATURAL_COMM> _EO_NATURAL_COMM;
        /// <summary>
        /// There are no comments for EO_PLANT in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EO_PLANT> EO_PLANT
        {
            get
            {
                if ((this._EO_PLANT == null))
                {
                    this._EO_PLANT = base.CreateQuery<EO_PLANT>("[EO_PLANT]");
                }
                return this._EO_PLANT;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EO_PLANT> _EO_PLANT;
        /// <summary>
        /// There are no comments for EO_ANIMAL in the schema.
        /// </summary>
        public void AddToEO_ANIMAL(EO_ANIMAL eO_ANIMAL)
        {
            base.AddObject("EO_ANIMAL", eO_ANIMAL);
        }
        /// <summary>
        /// There are no comments for EO_NATURAL_COMM in the schema.
        /// </summary>
        public void AddToEO_NATURAL_COMM(EO_NATURAL_COMM eO_NATURAL_COMM)
        {
            base.AddObject("EO_NATURAL_COMM", eO_NATURAL_COMM);
        }
        /// <summary>
        /// There are no comments for EO_PLANT in the schema.
        /// </summary>
        public void AddToEO_PLANT(EO_PLANT eO_PLANT)
        {
            base.AddObject("EO_PLANT", eO_PLANT);
        }
    }
    /// <summary>
    /// There are no comments for RestdModel.EO_ANIMAL in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ELCODE
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RestdModel", Name="EO_ANIMAL")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EO_ANIMAL : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EO_ANIMAL object.
        /// </summary>
        /// <param name="eLCODE">Initial value of ELCODE.</param>
        public static EO_ANIMAL CreateEO_ANIMAL(string eLCODE)
        {
            EO_ANIMAL eO_ANIMAL = new EO_ANIMAL();
            eO_ANIMAL.ELCODE = eLCODE;
            return eO_ANIMAL;
        }
        /// <summary>
        /// There are no comments for Property ELCODE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ELCODE
        {
            get
            {
                return this._ELCODE;
            }
            set
            {
                this.OnELCODEChanging(value);
                this.ReportPropertyChanging("ELCODE");
                this._ELCODE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ELCODE");
                this.OnELCODEChanged();
            }
        }
        private string _ELCODE;
        partial void OnELCODEChanging(string value);
        partial void OnELCODEChanged();
        /// <summary>
        /// There are no comments for Property SCIENTIFIC_NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SCIENTIFIC_NAME
        {
            get
            {
                return this._SCIENTIFIC_NAME;
            }
            set
            {
                this.OnSCIENTIFIC_NAMEChanging(value);
                this.ReportPropertyChanging("SCIENTIFIC_NAME");
                this._SCIENTIFIC_NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SCIENTIFIC_NAME");
                this.OnSCIENTIFIC_NAMEChanged();
            }
        }
        private string _SCIENTIFIC_NAME;
        partial void OnSCIENTIFIC_NAMEChanging(string value);
        partial void OnSCIENTIFIC_NAMEChanged();
        /// <summary>
        /// There are no comments for Property COMMON_NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMON_NAME
        {
            get
            {
                return this._COMMON_NAME;
            }
            set
            {
                this.OnCOMMON_NAMEChanging(value);
                this.ReportPropertyChanging("COMMON_NAME");
                this._COMMON_NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("COMMON_NAME");
                this.OnCOMMON_NAMEChanged();
            }
        }
        private string _COMMON_NAME;
        partial void OnCOMMON_NAMEChanging(string value);
        partial void OnCOMMON_NAMEChanged();
        /// <summary>
        /// There are no comments for Property FAMILY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FAMILY
        {
            get
            {
                return this._FAMILY;
            }
            set
            {
                this.OnFAMILYChanging(value);
                this.ReportPropertyChanging("FAMILY");
                this._FAMILY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FAMILY");
                this.OnFAMILYChanged();
            }
        }
        private string _FAMILY;
        partial void OnFAMILYChanging(string value);
        partial void OnFAMILYChanged();
        /// <summary>
        /// There are no comments for Property STATE_STATUS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string STATE_STATUS
        {
            get
            {
                return this._STATE_STATUS;
            }
            set
            {
                this.OnSTATE_STATUSChanging(value);
                this.ReportPropertyChanging("STATE_STATUS");
                this._STATE_STATUS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("STATE_STATUS");
                this.OnSTATE_STATUSChanged();
            }
        }
        private string _STATE_STATUS;
        partial void OnSTATE_STATUSChanging(string value);
        partial void OnSTATE_STATUSChanged();
        /// <summary>
        /// There are no comments for Property FED_STATUS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FED_STATUS
        {
            get
            {
                return this._FED_STATUS;
            }
            set
            {
                this.OnFED_STATUSChanging(value);
                this.ReportPropertyChanging("FED_STATUS");
                this._FED_STATUS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FED_STATUS");
                this.OnFED_STATUSChanged();
            }
        }
        private string _FED_STATUS;
        partial void OnFED_STATUSChanging(string value);
        partial void OnFED_STATUSChanged();
        /// <summary>
        /// There are no comments for Property S_RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string S_RANK
        {
            get
            {
                return this._S_RANK;
            }
            set
            {
                this.OnS_RANKChanging(value);
                this.ReportPropertyChanging("S_RANK");
                this._S_RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("S_RANK");
                this.OnS_RANKChanged();
            }
        }
        private string _S_RANK;
        partial void OnS_RANKChanging(string value);
        partial void OnS_RANKChanged();
        /// <summary>
        /// There are no comments for Property G_RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string G_RANK
        {
            get
            {
                return this._G_RANK;
            }
            set
            {
                this.OnG_RANKChanging(value);
                this.ReportPropertyChanging("G_RANK");
                this._G_RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("G_RANK");
                this.OnG_RANKChanged();
            }
        }
        private string _G_RANK;
        partial void OnG_RANKChanging(string value);
        partial void OnG_RANKChanged();
        /// <summary>
        /// There are no comments for Property NE_RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NE_RANK
        {
            get
            {
                return this._NE_RANK;
            }
            set
            {
                this.OnNE_RANKChanging(value);
                this.ReportPropertyChanging("NE_RANK");
                this._NE_RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NE_RANK");
                this.OnNE_RANKChanged();
            }
        }
        private string _NE_RANK;
        partial void OnNE_RANKChanging(string value);
        partial void OnNE_RANKChanged();
        /// <summary>
        /// There are no comments for Property RFR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RFR
        {
            get
            {
                return this._RFR;
            }
            set
            {
                this.OnRFRChanging(value);
                this.ReportPropertyChanging("RFR");
                this._RFR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RFR");
                this.OnRFRChanged();
            }
        }
        private string _RFR;
        partial void OnRFRChanging(string value);
        partial void OnRFRChanged();
        /// <summary>
        /// There are no comments for Property THREATS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string THREATS
        {
            get
            {
                return this._THREATS;
            }
            set
            {
                this.OnTHREATSChanging(value);
                this.ReportPropertyChanging("THREATS");
                this._THREATS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("THREATS");
                this.OnTHREATSChanged();
            }
        }
        private string _THREATS;
        partial void OnTHREATSChanging(string value);
        partial void OnTHREATSChanged();
        /// <summary>
        /// There are no comments for Property CONSERVATION_CON in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CONSERVATION_CON
        {
            get
            {
                return this._CONSERVATION_CON;
            }
            set
            {
                this.OnCONSERVATION_CONChanging(value);
                this.ReportPropertyChanging("CONSERVATION_CON");
                this._CONSERVATION_CON = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CONSERVATION_CON");
                this.OnCONSERVATION_CONChanged();
            }
        }
        private string _CONSERVATION_CON;
        partial void OnCONSERVATION_CONChanging(string value);
        partial void OnCONSERVATION_CONChanged();
        /// <summary>
        /// There are no comments for Property HABITAT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HABITAT
        {
            get
            {
                return this._HABITAT;
            }
            set
            {
                this.OnHABITATChanging(value);
                this.ReportPropertyChanging("HABITAT");
                this._HABITAT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("HABITAT");
                this.OnHABITATChanged();
            }
        }
        private string _HABITAT;
        partial void OnHABITATChanging(string value);
        partial void OnHABITATChanged();
        /// <summary>
        /// There are no comments for Property RANGE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RANGE
        {
            get
            {
                return this._RANGE;
            }
            set
            {
                this.OnRANGEChanging(value);
                this.ReportPropertyChanging("RANGE");
                this._RANGE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RANGE");
                this.OnRANGEChanged();
            }
        }
        private string _RANGE;
        partial void OnRANGEChanging(string value);
        partial void OnRANGEChanged();
        /// <summary>
        /// There are no comments for Property STATE_DISTRIBUTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string STATE_DISTRIBUTION
        {
            get
            {
                return this._STATE_DISTRIBUTION;
            }
            set
            {
                this.OnSTATE_DISTRIBUTIONChanging(value);
                this.ReportPropertyChanging("STATE_DISTRIBUTION");
                this._STATE_DISTRIBUTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("STATE_DISTRIBUTION");
                this.OnSTATE_DISTRIBUTIONChanged();
            }
        }
        private string _STATE_DISTRIBUTION;
        partial void OnSTATE_DISTRIBUTIONChanging(string value);
        partial void OnSTATE_DISTRIBUTIONChanged();
        /// <summary>
        /// There are no comments for Property GLOBAL_DISTRIBUTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string GLOBAL_DISTRIBUTION
        {
            get
            {
                return this._GLOBAL_DISTRIBUTION;
            }
            set
            {
                this.OnGLOBAL_DISTRIBUTIONChanging(value);
                this.ReportPropertyChanging("GLOBAL_DISTRIBUTION");
                this._GLOBAL_DISTRIBUTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GLOBAL_DISTRIBUTION");
                this.OnGLOBAL_DISTRIBUTIONChanged();
            }
        }
        private string _GLOBAL_DISTRIBUTION;
        partial void OnGLOBAL_DISTRIBUTIONChanging(string value);
        partial void OnGLOBAL_DISTRIBUTIONChanged();
        /// <summary>
        /// There are no comments for Property IDENTIFICATION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IDENTIFICATION
        {
            get
            {
                return this._IDENTIFICATION;
            }
            set
            {
                this.OnIDENTIFICATIONChanging(value);
                this.ReportPropertyChanging("IDENTIFICATION");
                this._IDENTIFICATION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("IDENTIFICATION");
                this.OnIDENTIFICATIONChanged();
            }
        }
        private string _IDENTIFICATION;
        partial void OnIDENTIFICATIONChanging(string value);
        partial void OnIDENTIFICATIONChanged();
        /// <summary>
        /// There are no comments for Property PHENOLOGY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PHENOLOGY
        {
            get
            {
                return this._PHENOLOGY;
            }
            set
            {
                this.OnPHENOLOGYChanging(value);
                this.ReportPropertyChanging("PHENOLOGY");
                this._PHENOLOGY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PHENOLOGY");
                this.OnPHENOLOGYChanged();
            }
        }
        private string _PHENOLOGY;
        partial void OnPHENOLOGYChanging(string value);
        partial void OnPHENOLOGYChanged();
        /// <summary>
        /// There are no comments for Property REFERENCES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string REFERENCES
        {
            get
            {
                return this._REFERENCES;
            }
            set
            {
                this.OnREFERENCESChanging(value);
                this.ReportPropertyChanging("REFERENCES");
                this._REFERENCES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("REFERENCES");
                this.OnREFERENCESChanged();
            }
        }
        private string _REFERENCES;
        partial void OnREFERENCESChanging(string value);
        partial void OnREFERENCESChanged();
    }
    /// <summary>
    /// There are no comments for RestdModel.EO_NATURAL_COMM in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MNAP_CODE
    /// ELCODE
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RestdModel", Name="EO_NATURAL_COMM")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EO_NATURAL_COMM : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EO_NATURAL_COMM object.
        /// </summary>
        /// <param name="mNAP_CODE">Initial value of MNAP_CODE.</param>
        /// <param name="eLCODE">Initial value of ELCODE.</param>
        public static EO_NATURAL_COMM CreateEO_NATURAL_COMM(string mNAP_CODE, string eLCODE)
        {
            EO_NATURAL_COMM eO_NATURAL_COMM = new EO_NATURAL_COMM();
            eO_NATURAL_COMM.MNAP_CODE = mNAP_CODE;
            eO_NATURAL_COMM.ELCODE = eLCODE;
            return eO_NATURAL_COMM;
        }
        /// <summary>
        /// There are no comments for Property MNAP_CODE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string MNAP_CODE
        {
            get
            {
                return this._MNAP_CODE;
            }
            set
            {
                this.OnMNAP_CODEChanging(value);
                this.ReportPropertyChanging("MNAP_CODE");
                this._MNAP_CODE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("MNAP_CODE");
                this.OnMNAP_CODEChanged();
            }
        }
        private string _MNAP_CODE;
        partial void OnMNAP_CODEChanging(string value);
        partial void OnMNAP_CODEChanged();
        /// <summary>
        /// There are no comments for Property ELCODE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ELCODE
        {
            get
            {
                return this._ELCODE;
            }
            set
            {
                this.OnELCODEChanging(value);
                this.ReportPropertyChanging("ELCODE");
                this._ELCODE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ELCODE");
                this.OnELCODEChanged();
            }
        }
        private string _ELCODE;
        partial void OnELCODEChanging(string value);
        partial void OnELCODEChanged();
        /// <summary>
        /// There are no comments for Property ME_SCI_NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ME_SCI_NAME
        {
            get
            {
                return this._ME_SCI_NAME;
            }
            set
            {
                this.OnME_SCI_NAMEChanging(value);
                this.ReportPropertyChanging("ME_SCI_NAME");
                this._ME_SCI_NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ME_SCI_NAME");
                this.OnME_SCI_NAMEChanged();
            }
        }
        private string _ME_SCI_NAME;
        partial void OnME_SCI_NAMEChanging(string value);
        partial void OnME_SCI_NAMEChanged();
        /// <summary>
        /// There are no comments for Property ME_COMMON_NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ME_COMMON_NAME
        {
            get
            {
                return this._ME_COMMON_NAME;
            }
            set
            {
                this.OnME_COMMON_NAMEChanging(value);
                this.ReportPropertyChanging("ME_COMMON_NAME");
                this._ME_COMMON_NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ME_COMMON_NAME");
                this.OnME_COMMON_NAMEChanged();
            }
        }
        private string _ME_COMMON_NAME;
        partial void OnME_COMMON_NAMEChanging(string value);
        partial void OnME_COMMON_NAMEChanged();
        /// <summary>
        /// There are no comments for Property S_RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string S_RANK
        {
            get
            {
                return this._S_RANK;
            }
            set
            {
                this.OnS_RANKChanging(value);
                this.ReportPropertyChanging("S_RANK");
                this._S_RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("S_RANK");
                this.OnS_RANKChanged();
            }
        }
        private string _S_RANK;
        partial void OnS_RANKChanging(string value);
        partial void OnS_RANKChanged();
        /// <summary>
        /// There are no comments for Property CONSERVATION_CON in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CONSERVATION_CON
        {
            get
            {
                return this._CONSERVATION_CON;
            }
            set
            {
                this.OnCONSERVATION_CONChanging(value);
                this.ReportPropertyChanging("CONSERVATION_CON");
                this._CONSERVATION_CON = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CONSERVATION_CON");
                this.OnCONSERVATION_CONChanged();
            }
        }
        private string _CONSERVATION_CON;
        partial void OnCONSERVATION_CONChanging(string value);
        partial void OnCONSERVATION_CONChanged();
        /// <summary>
        /// There are no comments for Property WILDLIFE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string WILDLIFE
        {
            get
            {
                return this._WILDLIFE;
            }
            set
            {
                this.OnWILDLIFEChanging(value);
                this.ReportPropertyChanging("WILDLIFE");
                this._WILDLIFE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("WILDLIFE");
                this.OnWILDLIFEChanged();
            }
        }
        private string _WILDLIFE;
        partial void OnWILDLIFEChanging(string value);
        partial void OnWILDLIFEChanged();
        /// <summary>
        /// There are no comments for Property DISTRIBUTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DISTRIBUTION
        {
            get
            {
                return this._DISTRIBUTION;
            }
            set
            {
                this.OnDISTRIBUTIONChanging(value);
                this.ReportPropertyChanging("DISTRIBUTION");
                this._DISTRIBUTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DISTRIBUTION");
                this.OnDISTRIBUTIONChanged();
            }
        }
        private string _DISTRIBUTION;
        partial void OnDISTRIBUTIONChanging(string value);
        partial void OnDISTRIBUTIONChanged();
        /// <summary>
        /// There are no comments for Property DESCRIPTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION
        {
            get
            {
                return this._DESCRIPTION;
            }
            set
            {
                this.OnDESCRIPTIONChanging(value);
                this.ReportPropertyChanging("DESCRIPTION");
                this._DESCRIPTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DESCRIPTION");
                this.OnDESCRIPTIONChanged();
            }
        }
        private string _DESCRIPTION;
        partial void OnDESCRIPTIONChanging(string value);
        partial void OnDESCRIPTIONChanged();
        /// <summary>
        /// There are no comments for Property SOIL_SITE_DESC in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SOIL_SITE_DESC
        {
            get
            {
                return this._SOIL_SITE_DESC;
            }
            set
            {
                this.OnSOIL_SITE_DESCChanging(value);
                this.ReportPropertyChanging("SOIL_SITE_DESC");
                this._SOIL_SITE_DESC = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SOIL_SITE_DESC");
                this.OnSOIL_SITE_DESCChanged();
            }
        }
        private string _SOIL_SITE_DESC;
        partial void OnSOIL_SITE_DESCChanging(string value);
        partial void OnSOIL_SITE_DESCChanged();
        /// <summary>
        /// There are no comments for Property DIAGNOSTICS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string DIAGNOSTICS
        {
            get
            {
                return this._DIAGNOSTICS;
            }
            set
            {
                this.OnDIAGNOSTICSChanging(value);
                this.ReportPropertyChanging("DIAGNOSTICS");
                this._DIAGNOSTICS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("DIAGNOSTICS");
                this.OnDIAGNOSTICSChanged();
            }
        }
        private string _DIAGNOSTICS;
        partial void OnDIAGNOSTICSChanging(string value);
        partial void OnDIAGNOSTICSChanged();
        /// <summary>
        /// There are no comments for Property SIMILAR_TYPES in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SIMILAR_TYPES
        {
            get
            {
                return this._SIMILAR_TYPES;
            }
            set
            {
                this.OnSIMILAR_TYPESChanging(value);
                this.ReportPropertyChanging("SIMILAR_TYPES");
                this._SIMILAR_TYPES = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SIMILAR_TYPES");
                this.OnSIMILAR_TYPESChanged();
            }
        }
        private string _SIMILAR_TYPES;
        partial void OnSIMILAR_TYPESChanging(string value);
        partial void OnSIMILAR_TYPESChanged();
        /// <summary>
        /// There are no comments for Property LANDSCAPE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LANDSCAPE
        {
            get
            {
                return this._LANDSCAPE;
            }
            set
            {
                this.OnLANDSCAPEChanging(value);
                this.ReportPropertyChanging("LANDSCAPE");
                this._LANDSCAPE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LANDSCAPE");
                this.OnLANDSCAPEChanged();
            }
        }
        private string _LANDSCAPE;
        partial void OnLANDSCAPEChanging(string value);
        partial void OnLANDSCAPEChanged();
    }
    /// <summary>
    /// There are no comments for RestdModel.EO_PLANT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ELCODE
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="RestdModel", Name="EO_PLANT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EO_PLANT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EO_PLANT object.
        /// </summary>
        /// <param name="eLCODE">Initial value of ELCODE.</param>
        public static EO_PLANT CreateEO_PLANT(string eLCODE)
        {
            EO_PLANT eO_PLANT = new EO_PLANT();
            eO_PLANT.ELCODE = eLCODE;
            return eO_PLANT;
        }
        /// <summary>
        /// There are no comments for Property ELCODE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ELCODE
        {
            get
            {
                return this._ELCODE;
            }
            set
            {
                this.OnELCODEChanging(value);
                this.ReportPropertyChanging("ELCODE");
                this._ELCODE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ELCODE");
                this.OnELCODEChanged();
            }
        }
        private string _ELCODE;
        partial void OnELCODEChanging(string value);
        partial void OnELCODEChanged();
        /// <summary>
        /// There are no comments for Property SCIENTIFIC_NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string SCIENTIFIC_NAME
        {
            get
            {
                return this._SCIENTIFIC_NAME;
            }
            set
            {
                this.OnSCIENTIFIC_NAMEChanging(value);
                this.ReportPropertyChanging("SCIENTIFIC_NAME");
                this._SCIENTIFIC_NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("SCIENTIFIC_NAME");
                this.OnSCIENTIFIC_NAMEChanged();
            }
        }
        private string _SCIENTIFIC_NAME;
        partial void OnSCIENTIFIC_NAMEChanging(string value);
        partial void OnSCIENTIFIC_NAMEChanged();
        /// <summary>
        /// There are no comments for Property COMMON_NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string COMMON_NAME
        {
            get
            {
                return this._COMMON_NAME;
            }
            set
            {
                this.OnCOMMON_NAMEChanging(value);
                this.ReportPropertyChanging("COMMON_NAME");
                this._COMMON_NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("COMMON_NAME");
                this.OnCOMMON_NAMEChanged();
            }
        }
        private string _COMMON_NAME;
        partial void OnCOMMON_NAMEChanging(string value);
        partial void OnCOMMON_NAMEChanged();
        /// <summary>
        /// There are no comments for Property FAMILY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FAMILY
        {
            get
            {
                return this._FAMILY;
            }
            set
            {
                this.OnFAMILYChanging(value);
                this.ReportPropertyChanging("FAMILY");
                this._FAMILY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FAMILY");
                this.OnFAMILYChanged();
            }
        }
        private string _FAMILY;
        partial void OnFAMILYChanging(string value);
        partial void OnFAMILYChanged();
        /// <summary>
        /// There are no comments for Property STATE_STATUS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string STATE_STATUS
        {
            get
            {
                return this._STATE_STATUS;
            }
            set
            {
                this.OnSTATE_STATUSChanging(value);
                this.ReportPropertyChanging("STATE_STATUS");
                this._STATE_STATUS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("STATE_STATUS");
                this.OnSTATE_STATUSChanged();
            }
        }
        private string _STATE_STATUS;
        partial void OnSTATE_STATUSChanging(string value);
        partial void OnSTATE_STATUSChanged();
        /// <summary>
        /// There are no comments for Property FED_STATUS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FED_STATUS
        {
            get
            {
                return this._FED_STATUS;
            }
            set
            {
                this.OnFED_STATUSChanging(value);
                this.ReportPropertyChanging("FED_STATUS");
                this._FED_STATUS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FED_STATUS");
                this.OnFED_STATUSChanged();
            }
        }
        private string _FED_STATUS;
        partial void OnFED_STATUSChanging(string value);
        partial void OnFED_STATUSChanged();
        /// <summary>
        /// There are no comments for Property S_RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string S_RANK
        {
            get
            {
                return this._S_RANK;
            }
            set
            {
                this.OnS_RANKChanging(value);
                this.ReportPropertyChanging("S_RANK");
                this._S_RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("S_RANK");
                this.OnS_RANKChanged();
            }
        }
        private string _S_RANK;
        partial void OnS_RANKChanging(string value);
        partial void OnS_RANKChanged();
        /// <summary>
        /// There are no comments for Property G_RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string G_RANK
        {
            get
            {
                return this._G_RANK;
            }
            set
            {
                this.OnG_RANKChanging(value);
                this.ReportPropertyChanging("G_RANK");
                this._G_RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("G_RANK");
                this.OnG_RANKChanged();
            }
        }
        private string _G_RANK;
        partial void OnG_RANKChanging(string value);
        partial void OnG_RANKChanged();
        /// <summary>
        /// There are no comments for Property NE_RANK in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NE_RANK
        {
            get
            {
                return this._NE_RANK;
            }
            set
            {
                this.OnNE_RANKChanging(value);
                this.ReportPropertyChanging("NE_RANK");
                this._NE_RANK = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NE_RANK");
                this.OnNE_RANKChanged();
            }
        }
        private string _NE_RANK;
        partial void OnNE_RANKChanging(string value);
        partial void OnNE_RANKChanged();
        /// <summary>
        /// There are no comments for Property RFR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RFR
        {
            get
            {
                return this._RFR;
            }
            set
            {
                this.OnRFRChanging(value);
                this.ReportPropertyChanging("RFR");
                this._RFR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RFR");
                this.OnRFRChanged();
            }
        }
        private string _RFR;
        partial void OnRFRChanging(string value);
        partial void OnRFRChanged();
        /// <summary>
        /// There are no comments for Property THREATS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string THREATS
        {
            get
            {
                return this._THREATS;
            }
            set
            {
                this.OnTHREATSChanging(value);
                this.ReportPropertyChanging("THREATS");
                this._THREATS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("THREATS");
                this.OnTHREATSChanged();
            }
        }
        private string _THREATS;
        partial void OnTHREATSChanging(string value);
        partial void OnTHREATSChanged();
        /// <summary>
        /// There are no comments for Property CONSERVATION_CON in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CONSERVATION_CON
        {
            get
            {
                return this._CONSERVATION_CON;
            }
            set
            {
                this.OnCONSERVATION_CONChanging(value);
                this.ReportPropertyChanging("CONSERVATION_CON");
                this._CONSERVATION_CON = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CONSERVATION_CON");
                this.OnCONSERVATION_CONChanged();
            }
        }
        private string _CONSERVATION_CON;
        partial void OnCONSERVATION_CONChanging(string value);
        partial void OnCONSERVATION_CONChanged();
        /// <summary>
        /// There are no comments for Property HABITAT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HABITAT
        {
            get
            {
                return this._HABITAT;
            }
            set
            {
                this.OnHABITATChanging(value);
                this.ReportPropertyChanging("HABITAT");
                this._HABITAT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("HABITAT");
                this.OnHABITATChanged();
            }
        }
        private string _HABITAT;
        partial void OnHABITATChanging(string value);
        partial void OnHABITATChanged();
        /// <summary>
        /// There are no comments for Property RANGE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string RANGE
        {
            get
            {
                return this._RANGE;
            }
            set
            {
                this.OnRANGEChanging(value);
                this.ReportPropertyChanging("RANGE");
                this._RANGE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RANGE");
                this.OnRANGEChanged();
            }
        }
        private string _RANGE;
        partial void OnRANGEChanging(string value);
        partial void OnRANGEChanged();
        /// <summary>
        /// There are no comments for Property STATE_DISTRIBUTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string STATE_DISTRIBUTION
        {
            get
            {
                return this._STATE_DISTRIBUTION;
            }
            set
            {
                this.OnSTATE_DISTRIBUTIONChanging(value);
                this.ReportPropertyChanging("STATE_DISTRIBUTION");
                this._STATE_DISTRIBUTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("STATE_DISTRIBUTION");
                this.OnSTATE_DISTRIBUTIONChanged();
            }
        }
        private string _STATE_DISTRIBUTION;
        partial void OnSTATE_DISTRIBUTIONChanging(string value);
        partial void OnSTATE_DISTRIBUTIONChanged();
        /// <summary>
        /// There are no comments for Property GLOBAL_DISTRIBUTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string GLOBAL_DISTRIBUTION
        {
            get
            {
                return this._GLOBAL_DISTRIBUTION;
            }
            set
            {
                this.OnGLOBAL_DISTRIBUTIONChanging(value);
                this.ReportPropertyChanging("GLOBAL_DISTRIBUTION");
                this._GLOBAL_DISTRIBUTION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("GLOBAL_DISTRIBUTION");
                this.OnGLOBAL_DISTRIBUTIONChanged();
            }
        }
        private string _GLOBAL_DISTRIBUTION;
        partial void OnGLOBAL_DISTRIBUTIONChanging(string value);
        partial void OnGLOBAL_DISTRIBUTIONChanged();
        /// <summary>
        /// There are no comments for Property IDENTIFICATION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IDENTIFICATION
        {
            get
            {
                return this._IDENTIFICATION;
            }
            set
            {
                this.OnIDENTIFICATIONChanging(value);
                this.ReportPropertyChanging("IDENTIFICATION");
                this._IDENTIFICATION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("IDENTIFICATION");
                this.OnIDENTIFICATIONChanged();
            }
        }
        private string _IDENTIFICATION;
        partial void OnIDENTIFICATIONChanging(string value);
        partial void OnIDENTIFICATIONChanged();
        /// <summary>
        /// There are no comments for Property PHENOLOGY in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PHENOLOGY
        {
            get
            {
                return this._PHENOLOGY;
            }
            set
            {
                this.OnPHENOLOGYChanging(value);
                this.ReportPropertyChanging("PHENOLOGY");
                this._PHENOLOGY = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PHENOLOGY");
                this.OnPHENOLOGYChanged();
            }
        }
        private string _PHENOLOGY;
        partial void OnPHENOLOGYChanging(string value);
        partial void OnPHENOLOGYChanged();
    }
}
